import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useQuery } from "@apollo/client";
import Layout from "../components/Layout";
import { GET_DATA } from "../graphql/query";
import UserTable from "../components/UserTable";
import CircularProgress from "@mui/material/CircularProgress";
import Container from "@mui/material/Container";
const Home: NextPage = () => {
  const {loading, error, data} = useQuery(GET_DATA)
  console.log(loading)
  console.log(error)

  console.log("data 1234", data)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        {loading ? <CircularProgress /> : null}
        {data ? <UserTable rows = {data.users.data} /> : null}
      </Container>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

// export async function getStaticProps() {
//   // const { data } = await client.query({
//   //   query: gql`
//   //   query {
//   //     album(id: 4) {
//   //       id
//   //       title
//   //       user {
//   //         name
//   //         username
//   //         email
//   //         phone
//   //       }
//   //     }
//   //   }
//   //   `
//   // });

//   const { data } = await client.query({
//     query: gql`
//       query {
//         posts(options:
//           {
//     paginate: {
//       page: 1,
//       limit: 100
  
//   }
//         }) {
//           data {
//             id
//             title
//           }
//           meta {
//             totalCount
//           }
//         }
//       }
//     `,
//   });

//   return {
//     props: {
//       data: data,
//     },
//   };
// }
